// HLTV World Ranking - December 1st, 2025
// Team logos from PandaScore CDN

import { TeamFull } from "./types";

// Top 20 teams from HLTV World Ranking with PandaScore logos
export const HLTV_TOP_TEAMS: TeamFull[] = [
    {
        id: 8297,
        name: "FURIA",
        logo: "https://cdn.pandascore.co/images/team/image/129384/600px_furia_esports.png",
        country: { name: "Brazil", code: "BR" },
        rank: 1,
        players: [
            { id: 2023, name: "Gabriel Toledo", ign: "FalleN", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 12553, name: "Yuri Santos", ign: "yuurih", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 13915, name: "Mareks Gaļinskis", ign: "YEKINDAR", image: "/player-placeholder.svg", country: { name: "Latvia", code: "LV" } },
            { id: 15631, name: "Kaike Cerato", ign: "KSCERATO", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 24144, name: "Danil Golubenko", ign: "molodoy", image: "/player-placeholder.svg", country: { name: "Kazakhstan", code: "KZ" } },
        ],
    },
    {
        id: 9565,
        name: "Vitality",
        logo: "https://cdn.pandascore.co/images/team/image/3455/team_vitalitylogo_square.png",
        country: { name: "France", code: "FR" },
        rank: 2,
        players: [
            { id: 7322, name: "Dan Madesclaire", ign: "apEX", image: "/player-placeholder.svg", country: { name: "France", code: "FR" } },
            { id: 11816, name: "Robin Kool", ign: "ropz", image: "/player-placeholder.svg", country: { name: "Estonia", code: "EE" } },
            { id: 11893, name: "Mathieu Herbaut", ign: "ZywOo", image: "/player-placeholder.svg", country: { name: "France", code: "FR" } },
            { id: 16693, name: "Shahar Shushan", ign: "flameZ", image: "/player-placeholder.svg", country: { name: "Israel", code: "IL" } },
            { id: 18462, name: "William Merriman", ign: "mezii", image: "/player-placeholder.svg", country: { name: "UK", code: "GB" } },
        ],
    },
    {
        id: 11283,
        name: "Falcons",
        logo: "https://cdn.pandascore.co/images/team/image/137508/183px_team_falcons_2022logo_square.png",
        country: { name: "International", code: "EU" },
        rank: 3,
        players: [
            { id: 3741, name: "Nikola Kovač", ign: "NiKo", image: "/player-placeholder.svg", country: { name: "Bosnia", code: "BA" } },
            { id: 12018, name: "René Madsen", ign: "TeSeS", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 19230, name: "Ilya Osipov", ign: "m0NESY", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 19677, name: "Damjan Stoilkovski", ign: "kyxsan", image: "/player-placeholder.svg", country: { name: "North Macedonia", code: "MK" } },
            { id: 24177, name: "Maxim Lukin", ign: "kyousuke", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
        ],
    },
    {
        id: 4494,
        name: "MOUZ",
        logo: "https://cdn.pandascore.co/images/team/image/86/mousesports-7bkq30ko.png",
        country: { name: "International", code: "EU" },
        rank: 4,
        players: [
            { id: 13666, name: "Ludvig Brolin", ign: "Brollan", image: "/player-placeholder.svg", country: { name: "Sweden", code: "SE" } },
            { id: 18072, name: "Ádám Torzsás", ign: "torzsi", image: "/player-placeholder.svg", country: { name: "Hungary", code: "HU" } },
            { id: 18221, name: "Lotan Giladi", ign: "Spinx", image: "/player-placeholder.svg", country: { name: "Israel", code: "IL" } },
            { id: 18850, name: "Jimi Salo", ign: "Jimpphat", image: "/player-placeholder.svg", country: { name: "Finland", code: "FI" } },
            { id: 20312, name: "Dorian Berman", ign: "xertioN", image: "/player-placeholder.svg", country: { name: "Israel", code: "IL" } },
        ],
    },
    {
        id: 6248,
        name: "The MongolZ",
        logo: "https://cdn.pandascore.co/images/team/image/130649/the_mongolz_2022_lightmode.png",
        country: { name: "Mongolia", code: "MN" },
        rank: 5,
        players: [
            { id: 20194, name: "Garidmagnai Byambasuren", ign: "bLitz", image: "/player-placeholder.svg", country: { name: "Mongolia", code: "MN" } },
            { id: 20275, name: "Sodbayar Munkhbold", ign: "Techno", image: "/player-placeholder.svg", country: { name: "Mongolia", code: "MN" } },
            { id: 21001, name: "Ayush Batbold", ign: "mzinho", image: "/player-placeholder.svg", country: { name: "Mongolia", code: "MN" } },
            { id: 21809, name: "Usukhbayar Banzragch", ign: "910", image: "/player-placeholder.svg", country: { name: "Mongolia", code: "MN" } },
        ],
    },
    {
        id: 7020,
        name: "Spirit",
        logo: "https://cdn.pandascore.co/images/team/image/3378/team_spirit_2023_logo.png",
        country: { name: "Russia", code: "RU" },
        rank: 6,
        players: [
            { id: 7716, name: "Leonid Vishnyakov", ign: "chopper", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 16920, name: "Dmitry Sokolov", ign: "sh1ro", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 19808, name: "Andrey Tatarinovich", ign: "tN1R", image: "/player-placeholder.svg", country: { name: "Belarus", code: "BY" } },
            { id: 21167, name: "Danil Kryshkovets", ign: "donk", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 23685, name: "Ivan Gogin", ign: "zweih", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
        ],
    },
    {
        id: 4608,
        name: "Natus Vincere",
        logo: "https://cdn.pandascore.co/images/team/image/3216/natus_vincerenew.png",
        country: { name: "Ukraine", code: "UA" },
        rank: 7,
        players: [
            { id: 9816, name: "Aleksi Virolainen", ign: "Aleksib", image: "/player-placeholder.svg", country: { name: "Finland", code: "FI" } },
            { id: 14759, name: "Mihai Ivan", ign: "iM", image: "/player-placeholder.svg", country: { name: "Romania", code: "RO" } },
            { id: 18987, name: "Valeriy Vakhovskiy", ign: "b1t", image: "/player-placeholder.svg", country: { name: "Ukraine", code: "UA" } },
            { id: 20127, name: "Ihor Zhdanov", ign: "w0nderful", image: "/player-placeholder.svg", country: { name: "Ukraine", code: "UA" } },
            { id: 22673, name: "Drin Shaqiri", ign: "makazze", image: "/player-placeholder.svg", country: { name: "Kosovo", code: "XK" } },
        ],
    },
    {
        id: 5995,
        name: "G2",
        logo: "https://cdn.pandascore.co/images/team/image/3210/g2-esports.png",
        country: { name: "International", code: "EU" },
        rank: 8,
        players: [
            { id: 3972, name: "Nemanja Kovač", ign: "huNter-", image: "/player-placeholder.svg", country: { name: "Bosnia", code: "BA" } },
            { id: 11617, name: "Mario Samayoa", ign: "malbsMd", image: "/player-placeholder.svg", country: { name: "Guatemala", code: "GT" } },
            { id: 19164, name: "Álvaro García", ign: "SunPayus", image: "/player-placeholder.svg", country: { name: "Spain", code: "ES" } },
            { id: 20447, name: "Nikita Martynenko", ign: "HeavyGod", image: "/player-placeholder.svg", country: { name: "Israel", code: "IL" } },
            { id: 21062, name: "Matúš Šimko", ign: "MATYS", image: "/player-placeholder.svg", country: { name: "Slovakia", code: "SK" } },
        ],
    },
    {
        id: 11861,
        name: "Aurora",
        logo: "https://cdn.pandascore.co/images/team/image/127266/eternal_fire_2021_allmode.png",
        country: { name: "Turkey", code: "TR" },
        rank: 9,
        players: [
            { id: 150, name: "Engin Küpeli", ign: "MAJ3R", image: "/player-placeholder.svg", country: { name: "Turkey", code: "TR" } },
            { id: 7938, name: "Ismailcan Dörtkardeş", ign: "XANTARES", image: "/player-placeholder.svg", country: { name: "Turkey", code: "TR" } },
            { id: 8574, name: "Özgür Eker", ign: "woxic", image: "/player-placeholder.svg", country: { name: "Turkey", code: "TR" } },
            { id: 21243, name: "Ali Haydar Yalçın", ign: "Wicadia", image: "/player-placeholder.svg", country: { name: "Turkey", code: "TR" } },
            { id: 22361, name: "Samet Köklü", ign: "jottAAA", image: "/player-placeholder.svg", country: { name: "Turkey", code: "TR" } },
        ],
    },
    {
        id: 4773,
        name: "paiN",
        logo: "https://cdn.pandascore.co/images/team/image/3247/pain-gaming-f2ldjy01.png",
        country: { name: "Brazil", code: "BR" },
        rank: 10,
        players: [
            { id: 14736, name: "Franco Garcia", ign: "dgt", image: "/player-placeholder.svg", country: { name: "Uruguay", code: "UY" } },
            { id: 18141, name: "Rodrigo Bittencourt", ign: "biguzera", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 18865, name: "David Tapia Maldonado", ign: "dav1deuS", image: "/player-placeholder.svg", country: { name: "Chile", code: "CL" } },
            { id: 19694, name: "Lucas Soares", ign: "nqz", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 20171, name: "João Vinicius", ign: "snow", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
        ],
    },
    {
        id: 6665,
        name: "Astralis",
        logo: "https://cdn.pandascore.co/images/team/image/3204/astralis-gliut4cn.png",
        country: { name: "Denmark", code: "DK" },
        rank: 11,
        players: [
            { id: 7592, name: "Nicolai Reedtz", ign: "device", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 9032, name: "Emil Reif", ign: "Magisk", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 10096, name: "Rasmus Nielsen", ign: "HooXi", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 17956, name: "Jakob Nygaard", ign: "jabbi", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 20304, name: "Victor Staehr", ign: "Staehr", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
        ],
    },
    {
        id: 6667,
        name: "FaZe",
        logo: "https://cdn.pandascore.co/images/team/image/3232/faze-clan.png",
        country: { name: "International", code: "EU" },
        rank: 12,
        players: [
            { id: 429, name: "Finn Andersen", ign: "karrigan", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 9960, name: "David Čerňanský", ign: "frozen", image: "/player-placeholder.svg", country: { name: "Slovakia", code: "SK" } },
            { id: 10394, name: "Russel Van Dulken", ign: "Twistzz", image: "/player-placeholder.svg", country: { name: "Canada", code: "CA" } },
            { id: 18053, name: "Helvijs Saukants", ign: "broky", image: "/player-placeholder.svg", country: { name: "Latvia", code: "LV" } },
            { id: 22383, name: "Jakub Pietruszewski", ign: "jcobbb", image: "/player-placeholder.svg", country: { name: "Poland", code: "PL" } },
        ],
    },
    {
        id: 4914,
        name: "3DMAX",
        logo: "https://cdn.pandascore.co/images/team/image/129706/3dmax_2021_lightmode.png",
        country: { name: "France", code: "FR" },
        rank: 13,
        players: [
            { id: 8374, name: "Alexandre Pianaro", ign: "bodyy", image: "/player-placeholder.svg", country: { name: "France", code: "FR" } },
            { id: 13138, name: "Bryan Canda", ign: "Maka", image: "/player-placeholder.svg", country: { name: "France", code: "FR" } },
            { id: 13497, name: "Lucas Chastang", ign: "Lucky", image: "/player-placeholder.svg", country: { name: "France", code: "FR" } },
            { id: 19739, name: "Pierre Bulinge", ign: "Ex3rcice", image: "/player-placeholder.svg", country: { name: "France", code: "FR" } },
            { id: 21969, name: "Filip Brankovic", ign: "Graviti", image: "/player-placeholder.svg", country: { name: "France", code: "FR" } },
        ],
    },
    {
        id: 12468,
        name: "Legacy",
        logo: "https://cdn.pandascore.co/images/team/image/131155/legacy_esports_brazil_logo.png",
        country: { name: "Brazil", code: "BR" },
        rank: 14,
        players: [
            { id: 15698, name: "Eduardo Wolkmer", ign: "dumau", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 19045, name: "Bruno Rebelatto", ign: "latto", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 19686, name: "Vinicius Pereira", ign: "n1ssim", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 20563, name: "Lucas Meneghini", ign: "lux", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
            { id: 22965, name: "Guilherme Pacheco", ign: "saadzin", image: "/player-placeholder.svg", country: { name: "Brazil", code: "BR" } },
        ],
    },
    {
        id: 5973,
        name: "Liquid",
        logo: "https://cdn.pandascore.co/images/team/image/3246/600px_team_liquid_2023.png",
        country: { name: "USA", code: "US" },
        rank: 15,
        players: [
            { id: 8520, name: "Keith Markovic", ign: "NAF", image: "/player-placeholder.svg", country: { name: "Canada", code: "CA" } },
            { id: 8738, name: "Jonathan Jablonowski", ign: "EliGE", image: "/player-placeholder.svg", country: { name: "USA", code: "US" } },
            { id: 9436, name: "Guy Iluz", ign: "NertZ", image: "/player-placeholder.svg", country: { name: "Israel", code: "IL" } },
            { id: 16820, name: "Kamil Szkaradek", ign: "siuhy", image: "/player-placeholder.svg", country: { name: "Poland", code: "PL" } },
            { id: 21763, name: "Roland Tomkowiak", ign: "ultimate", image: "/player-placeholder.svg", country: { name: "Poland", code: "PL" } },
        ],
    },
    {
        id: 11241,
        name: "B8",
        logo: "https://cdn.pandascore.co/images/team/image/137538/185px_b8_lightmode.png",
        country: { name: "Ukraine", code: "UA" },
        rank: 16,
        players: [
            { id: 19592, name: "Daniil Valitov", ign: "headtr1ck", image: "/player-placeholder.svg", country: { name: "Ukraine", code: "UA" } },
            { id: 20112, name: "Alexey Yarmoshchuk", ign: "alex666", image: "/player-placeholder.svg", country: { name: "Ukraine", code: "UA" } },
            { id: 21708, name: "Andrii Kukharskyi", ign: "npl", image: "/player-placeholder.svg", country: { name: "Ukraine", code: "UA" } },
            { id: 22842, name: "Artem Kapran", ign: "kensizor", image: "/player-placeholder.svg", country: { name: "Ukraine", code: "UA" } },
            { id: 23643, name: "Dmytro Tsvir", ign: "esenthial", image: "/player-placeholder.svg", country: { name: "Ukraine", code: "UA" } },
        ],
    },
    {
        id: 9928,
        name: "GamerLegion",
        logo: "https://cdn.pandascore.co/images/team/image/133983/1200px_gamer_legion_2024_lightmode.png",
        country: { name: "International", code: "EU" },
        rank: 17,
        players: [
            { id: 9278, name: "Fredrik Sterner", ign: "REZ", image: "/player-placeholder.svg", country: { name: "Sweden", code: "SE" } },
            { id: 16486, name: "Erik Gustafsson", ign: "ztr", image: "/player-placeholder.svg", country: { name: "Sweden", code: "SE" } },
            { id: 20301, name: "Sebastian Tauson Lindelof", ign: "Tauson", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 22279, name: "Oldřich Nový", ign: "PR", image: "/player-placeholder.svg", country: { name: "Czech Republic", code: "CZ" } },
            { id: 23766, name: "Milan Polowiec", ign: "hypex", image: "/player-placeholder.svg", country: { name: "Poland", code: "PL" } },
        ],
    },
    {
        id: 7175,
        name: "HEROIC",
        logo: "https://cdn.pandascore.co/images/team/image/3213/heroic-csgonew.png",
        country: { name: "Denmark", code: "DK" },
        rank: 18,
        players: [
            { id: 19187, name: "Yasin Koç", ign: "xfl0ud", image: "/player-placeholder.svg", country: { name: "Turkey", code: "TR" } },
            { id: 20119, name: "Linus Bergman", ign: "nilo", image: "/player-placeholder.svg", country: { name: "Sweden", code: "SE" } },
            { id: 21983, name: "Christoffer Storgaard", ign: "Chr1zN", image: "/player-placeholder.svg", country: { name: "Denmark", code: "DK" } },
            { id: 22047, name: "Simon Boije", ign: "yxngstxr", image: "/player-placeholder.svg", country: { name: "Sweden", code: "SE" } },
            { id: 23600, name: "Alimzhan Bitimbay", ign: "Alkaren", image: "/player-placeholder.svg", country: { name: "Kazakhstan", code: "KZ" } },
        ],
    },
    {
        id: 5378,
        name: "Virtus.pro",
        logo: "https://cdn.pandascore.co/images/team/image/3209/virtuspro.png",
        country: { name: "Russia", code: "RU" },
        rank: 19,
        players: [
            { id: 12732, name: "Evgenii Lebedev", ign: "FL1T", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 16947, name: "Ilya Zalutskiy", ign: "Perfecto", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 20101, name: "Petr Bolyshev", ign: "fame", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 23637, name: "Vladimir Krasikov", ign: "b1st", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
            { id: 24952, name: "Vadim Arkov", ign: "tO0RO", image: "/player-placeholder.svg", country: { name: "Russia", code: "RU" } },
        ],
    },
    {
        id: 10567,
        name: "SAW",
        logo: "https://cdn.pandascore.co/images/team/image/127296/saw_lightmode.png",
        country: { name: "Portugal", code: "PT" },
        rank: 20,
        players: [
            { id: 630, name: "Christopher Fernandes", ign: "MUTiRiS", image: "/player-placeholder.svg", country: { name: "Portugal", code: "PT" } },
            { id: 20462, name: "João Vieira", ign: "story", image: "/player-placeholder.svg", country: { name: "Portugal", code: "PT" } },
            { id: 21014, name: "André Gil", ign: "Ag1l", image: "/player-placeholder.svg", country: { name: "Portugal", code: "PT" } },
            { id: 22807, name: "António Barbosa", ign: "aragornN", image: "/player-placeholder.svg", country: { name: "Portugal", code: "PT" } },
            { id: 23140, name: "Adones Nobre", ign: "krazy", image: "/player-placeholder.svg", country: { name: "Portugal", code: "PT" } },
        ],
    },
];

export function getHLTVTeams(): TeamFull[] {
    return HLTV_TOP_TEAMS;
}

export function getHLTVTeamById(id: number): TeamFull | undefined {
    return HLTV_TOP_TEAMS.find((t) => t.id === id);
}
