/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { MeProfile } from "../../../../apps/api/src/modules/me/me.types";

export * as health from "./health";
export * as video_games from "./video_games";

/**
 * Return the currently authenticated user's profile.
 * @controller MeController.me
 * @path GET /me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return PlainFetcher.fetch(connection, {
    ...me.METADATA,
    template: me.METADATA.path,
    path: me.path(),
  });
}
export namespace me {
  export type Output = MeProfile;

  export const METADATA = {
    method: "GET",
    path: "/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/me";
}
