/**
 * @packageDocumentation
 * @module api.functional.video_games
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { VideoGame } from "../../../../../apps/api/src/modules/video-game/video-game.types";

/**
 * List every video game tracked by the platform, ordered by name.
 * @controller VideoGameController.list
 * @path GET /video-games
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(),
  });
}
export namespace list {
  export type Output = Array<VideoGame>;

  export const METADATA = {
    method: "GET",
    path: "/video-games",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/video-games";
}

/**
 * Get a single video game by its numeric id.
 * @controller VideoGameController.getById
 * @path GET /video-games/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: number,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = VideoGame;

  export const METADATA = {
    method: "GET",
    path: "/video-games/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: number) =>
    `/video-games/${encodeURIComponent(id?.toString() ?? "null")}`;
}
