/**
 * @packageDocumentation
 * @module api.functional.matches
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ListMatchesQuery } from "../../../../../apps/api/src/modules/match/match.controller";
import type { Match } from "../../../../../apps/api/src/modules/match/match.types";

/**
 * List matches for a given video game and status.
 * Defaults to upcoming Counter-Strike 2 matches.
 * @controller MatchController.list
 * @path GET /matches
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(
  connection: IConnection,
  query: ListMatchesQuery,
): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(query),
  });
}
export namespace list {
  export type Query = ListMatchesQuery;
  export type Output = Array<Match>;

  export const METADATA = {
    method: "GET",
    path: "/matches",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: list.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/matches";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * Fetch a single match by its numeric PandaScore id or slug.
 * @controller MatchController.getOne
 * @path GET /matches/:idOrSlug
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getOne(
  connection: IConnection,
  idOrSlug: string,
): Promise<getOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...getOne.METADATA,
    template: getOne.METADATA.path,
    path: getOne.path(idOrSlug),
  });
}
export namespace getOne {
  export type Output = Match;

  export const METADATA = {
    method: "GET",
    path: "/matches/:idOrSlug",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (idOrSlug: string) =>
    `/matches/${encodeURIComponent(idOrSlug?.toString() ?? "null")}`;
}
