/**
 * @packageDocumentation
 * @module api.functional.tournaments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ListTournamentsQuery } from "../../../../../apps/api/src/modules/tournament/tournament.controller";
import type {
  TournamentBuckets,
  Tournament,
} from "../../../../../apps/api/src/modules/tournament/tournament.types";

/**
 * List tournaments for a video game grouped into running, upcoming
 * and past. Defaults to Counter-Strike 2 when the query param is
 * missing.
 * @controller TournamentController.list
 * @path GET /tournaments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(
  connection: IConnection,
  query: ListTournamentsQuery,
): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(query),
  });
}
export namespace list {
  export type Query = ListTournamentsQuery;
  export type Output = TournamentBuckets;

  export const METADATA = {
    method: "GET",
    path: "/tournaments",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: list.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/tournaments";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * Fetch a single tournament by its numeric id or PandaScore slug.
 * @controller TournamentController.getOne
 * @path GET /tournaments/:idOrSlug
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getOne(
  connection: IConnection,
  idOrSlug: string,
): Promise<getOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...getOne.METADATA,
    template: getOne.METADATA.path,
    path: getOne.path(idOrSlug),
  });
}
export namespace getOne {
  export type Output = Tournament;

  export const METADATA = {
    method: "GET",
    path: "/tournaments/:idOrSlug",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (idOrSlug: string) =>
    `/tournaments/${encodeURIComponent(idOrSlug?.toString() ?? "null")}`;
}
